"""Add is_free to Lesson and create UserAccess

Revision ID: 2acdd74b8043
Revises: 4a6db1c4df14
Create Date: 2025-01-05 17:37:08.099422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2acdd74b8043'
down_revision = '4a6db1c4df14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_free', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('is_free')

    # ### end Alembic commands ###
